### ISSUE TITLE
Add “Edit this page in GitHub” links

### ISSUE THREAD

**Issue by victorb** [ipfs/docs#103]
Maybe I'm just used to OSS documentation to work this way, but I expected the GitHub icon to take me to the file on GitHub rather than a link to the IPFS organization.

Would make it really simple to contribute if it took users directly to the file.

**Comment by Mr0grog** [comment]
Good point! I think where the link goes now makes sense, given that it’s sitting next to Twitter and YouTube links, but I think it would be really useful to have an “edit this page in GitHub” link.

I think that’s as simple as adding something like:

```html
<a href="https://github.com/ipfs/docs/blob/master/{{ .File.Path }}" class="edit-page-link">
  Edit this page in GitHub
</a>
```

To the [footer](https://github.com/ipfs/docs/blob/master/layouts/partials/footer.html) or some other template.

Side note: I suppose we *could* replace the current GitHub link with this, but then we should remove the Twitter and YouTube links. That’s not too terrible because they are also in the sidebar.

**Comment by RestitutorOrbis** [comment]
I'd love to take this on if no one else is.

**Comment by andrew** [comment]
Fixed in https://github.com/ipfs/docs/pull/150, just deployed by @olizilla 🎉
