### ISSUE TITLE
Add search support

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/docs#113]
A previous version of this site had a very broken search implementation using [Lunr JS](https://lunrjs.com). We removed it because we didn’t have time to focus on it *and* on getting docs from all over IPFS organized, but it would be *really* lovely to bring this functionality back.

Things that need solving:

- Basic working search implementation. Hugo has some tools for generating search indexes that might be helpful: https://gohugo.io/tools/search/
- Design for how to incorporate search nicely with the rest of the site
- Implementation of that design

Another problem to keep in mind here is that a lot what’s currently in this site is links to pages in GitHub or to other sites. Are there any feasible ways to make sure some of those show up in search results? *We don’t need to worry about this right away.*

**Comment by meiqimichelle** [comment]
A built-in, out-of-the-box solid search is one reason to switch to Gitbook, one of the options discussed in #71 . On the other hand, we've got a bit of a team-wide consistency going on now with Hugo -- but there are also a few sites now using Gitbook for docs-like items. I doubt that solves the "but we link out to lots of sites" point (but I'm not sure *anything* does in a straightforward way, and building something like that should not be at the top of our priority list).

@olizilla @jessicaschilling @ericronne what do you think? Eventually moving (when we have time) the IPFS docs to Gitbook would also be a good excuse to do an information architecture and editing overhaul 🎉 (because I know how to party).

**Comment by jessicaschilling** [comment]
@meiqimichelle Agreed with all of the above. 😸

**Comment by meiqimichelle** [comment]
For the re-vamped IPFS Cluster site, we're looking into using https://www.algolia.com/, which integrates with Hugo and seems to have a free tier. More on that soon™.

**Comment by jessicaschilling** [comment]
Closing this issue, since good search is one of the major considerations in both the tech stack and user-facing features specifications work being done under #195 and #197 😄
