### ISSUE TITLE
Remove or fix info that's wrong or not-yet right

### ISSUE THREAD

**Issue by SidHarder** [ipfs/docs#12]
Outdated things like multidaddrs that are not valid anymore, in presentations and other material

**Comment by lgierth** [comment]
Updated title to: Remove or fix info that's wrong or not-yet right

In documentation cases, we want to strike out the wrong information, and I think we should add a "helpi fixing it" link.

---

This will sometimes be info that's not neccessarily wrong, but was just simplified in order to bring a point accross. In these cases, we should note it's simplified and optionally mention the correct form.

**Comment by Mr0grog** [comment]
Since we rebooted this repo, the site is live, and we have at least a little ongoing contribution, I’m marking this as fixed. Please comment if it should be re-opened.
