### ISSUE TITLE
There are duplicate arguments named 'arg' in the http api document

### ISSUE THREAD

**Issue by JiaJiaJiang** [ipfs/docs#157]
Such as this one https://docs.ipfs.io/reference/api/http/#api-v0-object-patch-add-link
and others on this page.
They have more than one arguments named `arg` which may be a wrong name or just a copy mistake.

**Comment by Mr0grog** [comment]
Hi @JiaJiaJiang, that’s actually intentional, and correct. There’s a little more info about how the `arg` argument is repeated at the top of the page: https://docs.ipfs.io/reference/api/http/#arguments

The HTTP API is effectively mapping your request to a function call in the IPFS server, and positional arguments are represented with `arg`. Requesting this URL:

```sh
http://localhost:5001/api/v0/object/patch/add-link?arg=Qmu...&arg=new-link-name&arg=Qmu2...&create=true
```

Is the same as this CLI command:

```sh
> ipfs object patch add-link Qmu... new-link-name Qmu2... --create
#                            ^      ^             ^─ third `arg`
#                            │      └─ second `arg`
#                            └─ first `arg`
```

Or this function call:

```js
// This is not an actual thing, but both JS and Go implementations have a
// function more-or-less like this:
ipfs.object.patch.addLink('Qmu...', 'new-link-name', 'Qmu2...', {create: true})
```

You’ll see similar patterns in a lot of other HTTP servers for creating lists. For example, Ruby-on-Rails’s built in querystring parsing uses `argument_name[]` with square brackets to denote that it should make an array with each occurrence of that querystring argument:

```sh
http://some-rails-app.com/api-endpoint?something[]=first&something[]=second
# Parses querystring as: { something: [ 'first', 'second' ] }
```

**Comment by JiaJiaJiang** [comment]
Oh,I was careless.
 Sorry for not reading from the head of the page and thank you for the mention.
