### ISSUE TITLE
Features List: Set up collaborative workspace

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#193]
Set up a collaborative workspace where the docs task force as a whole can contribute ideas for the features list:
- Make it tough to duplicate entries (because async) but easy to annotate others' entries with comments of your own (because async)
- Able to include links and screenshots
- Do we need a commenting feature so we can start inline discussions?
- Other considerations?

**Comment by ericronne** [comment]
[HackMD is a handy utility](https://hackmd.io/@63VSdG1dQ7azpAYFt0TkAQ/ipfs-docs-collabbing/edit), which uses markdown.

Since it's simply a markdown file, commenting falls far short of Google's level of slick. Aside from that, it's worth a look.

**Comment by jessicaschilling** [comment]
We may need to embed screenshots, if we get to the level of granularity of spec-ing out UI elements we particularly love. Looks like Google Sheets can do this now: https://gsuiteupdates.googleblog.com/2019/03/sheets-images-in-cells.html
And I believe you can comment on Google Sheets cells, too.
Maybe that's the right platform? But just talking out loud.

**Comment by ericronne** [comment]
Are you talking about reviews for a large number of screens in one place? If so, hackmd is not that, for sure. Sheets may be good for large-scale tracking, but i would hate to use it for anything visual.

Invision

**Comment by jessicaschilling** [comment]
I’d not imagine a large number of big screenshots, but would encourage whatever tool you use to support the ability to include some snips of screenshots without too much pain. Totally your call though.

**Comment by eshon** [comment]
PL has an Airtable account, but its a paid service (but good for embedding anything like images in a spreadsheet and cross-referencing UX features). 

If you ever need to open source or share this more widely with the community other tools might be better. 

A lot of projects just track features in giant Github issues (e.g. https://github.com/facebook/Docusaurus/issues/789) but they're dev-focused, but a HackMD + a Github repo for images might work ok.

**Comment by ericronne** [comment]
Ok i recommend the following for collabs. Discuss! …
- [Docs-site github issues](https://github.com/ipfs/docs/issues) for discrete / bite-sized design work, because **openness**, ease of getting context on a given topic (ie scrollable conversations within an issue), and permanence (accessible archives)
- [Invision](invisionapp.com) for wires and larger-scale design work, because advanced **prototyping features** and good commenting tools
- _**Try**_ [HackMD](https://hackmd.io/lLpPz5KCQ0aUweel92bvEg?both) for meeting notes at the 18 July IPFS Docs & UX hangout, because openness (natch), markdown is very portable / github friendly, it's the future (speculation? perhaps), and it's pretty [easy to learn](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

**Comment by ericronne** [comment]
Moving forward with the above recos, in the interest of keeping things rolling along. We can always revisit :)

**Comment by ericronne** [comment]
[Docsite features list](https://hackmd.io/qCel8CPkRtCZsAA-Oxeupw?both)
