### ISSUE TITLE
Make sure we're on the path to doing Docs properly

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/docs#2]
This will be satisfied when
- [ ] Everything is in motion towards finding a person to be the full-time owner of docs as a product
- [ ] We have a plan around what this person will be doing
- [ ] We have a plan for making "docs creation/management" part of our culture

**Comment by flyingzumwalt** [comment]
Identifying What the Docs Product owner will do
* Aspirational goal & list of responsibilities

Incorporating docs into culture
* code without docs or integration into UX _is not considered "finished"_
* making UX a stake in design/development process -- a "docs + UX!" voice to balance voices calling for "Specs! Specs!" or "Performance!"

**Comment by lgierth** [comment]
### Contributions / WTFM / Annotations

I've split this idea off the telescope notes because it's generic enough
to be applicable to any static website backed by a Github-like repo.
(And I figure it could even be adapted to other kinds of content/data repositories.)

This brings together annotations and pull requests.
The user gets a UI overlay which lets them leave comments, or propose concrete copy changes.
These change proposals will be combined into a daily/bidaily/weekly Pull Request
with one commit per proposal, so that proposals are regularly reviewed and merged in batches.

This hopefully reduces the overhead of:
- Onboarding users to Github, and license signoffs.
- Process around each change proposal, currently: PR, CI run, discussion, approval, merge.

It'll also prevent the inevitable increase in volume of Github notifications once we receive more docs PRs.

In the spirit of WTFM, this would make it fast and easy to write down some little learning, or correct a typo, and get it merged and published quickly, while keeping the maintenance burden on the receiving end low.

1. Overlay UI posts to one of several annotations "servers" (AS). (round-robin? quorum?)
  - Comment vs. Change proposal.
2. Probably want a swarm protocol for posting these annotations (could be based on pubsub too).
3. Every document has its own log of annotations.
4. AS receives posted annotation, and adds it to document's log.
5. AS possibly notifies IRC channel about a new incoming annotation.
6. AS opens daily PR with one commit per change proposal.
7. Server listens in IRC channel and PRs for feedback.
  - "annobot: merge 4a3b2c", "annobot: reject 4a3b2c" (removes from PR)
8. Notes
  - ipfs-pages takes care of rendering, and updating the dnslink. See TODO link
  - Include comments and info about change proposals in rendered page?
  - Login-with-Github to authenticate annotations?

**Comment by lgierth** [comment]
About WTFM, a GPL-like social agreement around knowledge: http://www.roaming-initiative.com/blog/posts/wtfm

**Comment by lgierth** [comment]
We're on *the path* now
