### ISSUE TITLE
Blank IPFS Documentation FAQ Page

### ISSUE THREAD

**Issue by pkafei** [ipfs/docs#213]
The [IPFS Documentation- FAQ Page](https://docs.ipfs.io/introduction/faq/) is blank. We could for now delete the page and replace links to the FAQ page to https://discuss.ipfs.io/c/help/Old-FAQ.

**Comment by momack2** [comment]
According to the docs - the blank page was created to add the external link to the discuss FAQ page to the sidenav on the left.

```title: FAQ
# This is a terrible hack to get external links in `section:` sections
# TODO: fix the nav so this isn't needed.
external: "https://discuss.ipfs.io/c/help/Old-FAQ" 
```

I would really like to see us have a usefully organized FAQ about IPFS instead of just linking to this hard-to-parse/search list directly. I've created a first draft here: https://github.com/ipfs/docs/pull/214 that with less than +2hrs of work should be MVP-worthy, but would love folks to run with this! Maybe @vasa-develop or @andrewxhill/@carsonfarmer have content from explainers they've created to contribute here?

Other questions I'd like to eventually see answered include:
- A better "what is IPFS" answer that has less jargon
- How does IPFS work?
- How is IPFS different from other file systems?
- How are IPFS and Filecoin related?
- Is all data added to IPFS permanent?
  - this confusion comes from the "permanent web" moniker - making people think that all data added is indefinitely persisted by some pervasive storage layer in IPFS, which is not the case.
- Can you have private / personal data on IPFS?

**Comment by tapaswenipathak** [comment]
Hi @pkafei, @momack2: Can I work on the ticket adding the old FAQs and listed questions?

**Comment by Stebalien** [comment]
@tapaswenipathak that would be wonderful! Note: you may need to clean up some of the "answers", many of them were discussions with lots of back-and-forth.

**Comment by jessicaschilling** [comment]
I'm going to close this one out since the original issue (the blank FAQ page) is remedied at a basic level -- however, the successor to this issue (fleshing out the FAQ page overall) is alive and could use some help at #223. Thanks all!
