### ISSUE TITLE
Reshuffle the Guides docs landing page to match the section contents

### ISSUE THREAD

**Issue by ericronne** [ipfs/docs#262]
**_This issue is part of [Epic 3B: Fixes from legacy issue queue](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++%22epic+3b%22+)._**

"Install" is noted twice on the [Guides index page](https://docs.ipfs.io/guides/), and neither summary is a good intro to the section to which it links. Remedy.

**Comment by jessicaschilling** [comment]
This is a little more complex than it looks at first, because it involves Hugo's auto-generated landing pages - just FYI.

**Comment by jessicaschilling** [comment]
See below for screenshot of a compromise solution -- since we're leaving Hugo behind with deployment of the docs beta, it didn't seem a good use of time to dig into its means of auto-generating content on page bundle index pages. 

What this does:
- Removes duplicate content
- Fixes typos and poor wording in original top-of-page text about install page
- Adds a prominent visual callout (in existing design language) at the top of the page leading to the install guide

What this doesn't do:
- Hide the poorly-formatted, auto-generated Hugo content at the bottom of the page for "install IPFS" or "addressing in browsers"

@ericronne, I'm taking the liberty of closing this issue, but please reach out if you want to iterate on it more! Thanks. 

![image](https://user-images.githubusercontent.com/1507828/67439519-aeac7680-f5b3-11e9-9a8a-f5bc8b81d9a5.png)
