### ISSUE TITLE
Host beta on IPFS

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#271]
Design, implement and test mechanisms necessary to host docs beta on IPFS. Note at this point there's still a large degree of uncertainty of the time this effort will take, as testing isn't easily defined at the moment.

**Comment by momack2** [comment]
Hey @cwaring - wondering what the status is on this. Is there any existing code/PRs to ensure our v2 beta site will be on IPFS? Would love to see the more detailed plan (and a due-by date) so we can also reflect that back to the folks at Ethereum who have a vuepress based site we'd like to get on IPFS.

**Comment by jessicaschilling** [comment]
@olizilla and I had a quick chat about this and https://github.com/olizilla/all-relative ... he may also have some additional input, too.

**Comment by cwaring** [comment]
Hi folks. No additional code has been written for this yet other than the prototype that I had running locally a while back.

We had a team meeting last week in order to triage the remaining [main priority tasks](https://github.com/ipfs/docs/milestone/3) towards the end of the year, this is the current order of implementation that we are working to (including this task).

If we wish to make this a higher priority and tackle it now, I'm happy to do so however it will delay some the end user functionality so we have to be mindful to ensure that I don't block the rest of the team.

Happy discuss further so that we can make a call on next steps.

**Comment by jessicaschilling** [comment]
Current agreed status as discussed in [Monday's WG call ](https://docs.google.com/document/d/1EOD-pJi4GvRmGi9HHocgVV8uVHMFIZlyVgJDkvC3DQ4/edit#heading=h.o81gxgtxn8am)...
- We are not approved to launch beta off IPFS
- That said, we have support for moving the initial mid-Dec launch date out to approx mid-Jan if needed
- We may be able to get some help from others within the IPFS core org (@olizilla and @lidel were specifically mentioned as either potential helpers, or advice to how to find helpers)

**Comment by momack2** [comment]
Thanks for the update. This is a blocker for a public launch / comms - so the question in my mind is if we can find others to pitch in on this. @cwaring  - can you link your draft PR with your local demo so we can keep track of that in one place?

Folks that come to mind that may have bandwidth (aka this is higher priority than their current projects) and expertise also include @dominguesgm @hugomrdias @pedromiguelss. David mentioned that @satazor was the hero behind getting the js.ipfs.io website on ipfs in time for launch - and may have some expertise and bandwidth to share as well (ideally with another owner). I'll start a thread about who might be able to jump in!

**Comment by hugomrdias** [comment]
Feel free to ping me I'll help !! Let's ship this ;)

**Comment by cwaring** [comment]
I've [updated a gist](https://gist.github.com/cwaring/d27a3330ad0334b0e96475b9ff808fae) with the steps necessary to post process a VuePress build and make it hash and IPNS aware so that is suitable for hosting on IPFS.

There is also a [related plugin](https://github.com/cwaring/vuepress-plugin-ipfs) with hooks setup so that we can begin to implement this and test the results.

More detailed plans to follow after discussions with @hugomrdias today.

**Comment by jessicaschilling** [comment]
Update: Next working session on this is happening between @cwaring and @hugomrdias tomorrow. Chris and Hugo - can you please update this issue with notes on that session?

**Comment by hugomrdias** [comment]
Just one note it works now :) 
https://github.com/ipfs/ipfs-docs-v2/pull/46

**Comment by jessicaschilling** [comment]
!!!!!!!

**Comment by cwaring** [comment]
ipfs/ipfs-docs-v2/pull/46 is merged to master, pending DNS changes this is now complete 🚀
