### ISSUE TITLE
Docs beta metrics collection: Define

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#310]
**_This issue is part of [Epic 2A: Define/implement beta site metrics collection](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++%22epic+2a%22)._**

Define the metrics to be collected in the new docs beta, with an aim toward using measures that lend themselves well to KPIs both now and in the future.

**Comment by jessicaschilling** [comment]
cc @mohnjatthews, since I can't assign him yet 😊

**Comment by johnnymatthews** [comment]
So there's two sets of metrics/analytics we can implement: _need_ and _nice_.

## Need

These are basic metrics that we can use to improve the general UX of the site.

1. Location/native language of user.
2. How they got to our docs (from Google, link from our Forum, somewhere else, etc).
3. Which pages they hit.
	a. How long they stayed on those pages.
	b. Which page they exited the docs on.

## Nice

While not 100% necessary, these metrics would help define our future targets and north-star goals.

1. Load time on each page.
2. What device they're using (mobile, tablet, laptop, smart watch, etc).
3. Anything they highlighted/clicked on.
4. Frequency of visits.

Thoughts @cwaring?

**Comment by jessicaschilling** [comment]
One other question ... other than the "helpful/not helpful" buttons, is there any measurement on the legacy site that we explicitly want to carry over to the new one? I believe that's all, but could just be forgetful.

**Comment by cwaring** [comment]
We should also capture outbound links so we can tally popular site exits.

**Comment by johnnymatthews** [comment]
# Docs beta metrics collection

This report dives into what metrics we should collect, why, and when we're going to use the data.

## Justification for metrics collection

The use of Google Analytics (GA) on a website aimed at distributing the web and improving the internet as a whole is relatively hypocritical. However, the fact is that GA offers the best metrics and analytics tools with minimal setup. Soon, the IPFS team plans to remove GA entirely from the documentation site and use either an open-source analytics tool or at least something less centralized.

With that in mind, we have attempted to select the least obtrusive and identifiable metrics available. We don't intend to sell or use any of the information collected by GA. The purpose of collecting these metrics is to find weak points in the documentation. Through this, we can improve the docs over time and make it easier for developers to build on IPFS.

## Metrics to collect

There are the following metrics we should collect from the IPFS documentation site and the justification for collecting said metrics.

### Need

The docs site should not launch without these metrics.

#### Native language of the user

The language that the user prefers to read. This metric helps us decide which languages to translate documentation into since translating into every single possible website isn't feasible right now.

#### Inbound link

Where the user comes from before hitting the site. This metric is likely going to be Google, the ipfs.io, or a forum link. Knowing where users are coming from tells our developer relations team where to focus their attention.

#### Pages hit

Which pages each user visits. This metric helps us know if a particular section is getting more attention than others, and if users are hopping around parts of the site a lot. With this information, we can structure the content of the docs to suit the habits of the users.

##### How long on each page

How many seconds users spend on each page, on average. This metric can help us decide how long a page should be. Do long articles work best or do users want to see smaller sized pages?

##### Exit page

Did the user leave the site on this page? This metric can tell us if a particular topic or page is frustrating users and causing them to abandon their efforts.

#### Helpful/not helpful buttons

Did the user find this page helpful or not? This metric comes from a widget that is attached to each page. It helps us find out which pages are frustrating users. Most users are more likely to interact with this widget when they're not getting the answers they want from the docs.

### Nice

These are the metrics and analytics that are nice to have but are not necessary to have at launch.

#### Page load time

How long the page is taking to load, on average. Combined with the other metrics, we can use this to see if load times are causing users to abandon their efforts.

#### Device

What device are users using to access the site? We're assuming that most users will be visiting the site on a desktop/laptop of some sort. However, if a large number of users are accessing our docs using mobile devices, we can put more emphasis on developing resources for those users.

#### Page interactions

Did the user click or highlight anything on the page? This metric allows us to define sections that the user finds valuable, such as code that they're copy-and-pasting frequently.

#### Frequency of visits

How many times does a particular user return to the docs site? This metric can help us find topics that users are getting stuck on, as well as pages that require several visits. Pages with long-form tutorials and API documentation will likely get a lot of hits.

#### Outbound exit links

Are the users leaving the docs site through an external link, GitHub or StackOverflow, for example? This metric can help our developer relations team to focus their attention on these platforms.

#### Search bar queries

What are users searching for, and are they clicking on the available results? This metric helps us find the topics the users want the most, or can't find in the sidebar navigation.

## Data Collection

Google Analytics anonymizes all data collected through it by default. We will not be using this data to identify particular users or their habits. The data will be aggregated every two to four weeks and made available publicly.

**Comment by jessicaschilling** [comment]
I've referred to @johnnymatthews' report in https://github.com/ipfs/docs/issues/310#issuecomment-562165787 in issue #311 for implementation -- @johnnymatthews and @cwaring, please implement as you're able. Thank you so much - closing this issue!
