### ISSUE TITLE
Route support requests to "help" section of discourse

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/docs#34]
In all the places where we say "for help, go to discourse", make it link to the "help" category rather than the main page.

Also write a nice orientation in [about the help category](https://discuss.ipfs.io/t/about-the-help-category/483) (currently it's the default starter text)

**Comment by Mr0grog** [comment]
@flyingzumwalt Any updates on this?

> In all the places where we say "for help, go to discourse", make it link to the "help" category rather than the main page.

- Is this effectively done or dropped and should be closed?
- Is it just really low priority? (Can/should other people help? How? Maybe by identifying a list of places in various repos this needs fixing?)
- Are you coming back around to work on it soon?

> write a nice orientation in [about the help category](
https://discuss.ipfs.io/t/about-the-help-category/483)

This one’s obviously *not* done; what’s the priority & status of it? Can someone draft better text here so you (or some other admin) can just drop it in? (@mikeal?)

**Comment by jessicaschilling** [comment]
Adding this one to the "OKR: Hotfixes" bucket ... in the hopes that it's something that can be reasonably easily solved via search/replace. If someone's able to take a quick look and investigate, that would be awesome -- it's definitely something that'd add to user convenience for the confused, but it's not a world-changer. Thanks!

**Comment by jessicaschilling** [comment]
Searching docs codebase for instances of this, and I believe they've all been ameliorated by now:
- no results for "discourse"
- 2 results for "forum" but they're not specific enough to direct people to the help section
- Various results for "support" but nothing relevant to this issue
- 6 results for "discuss" (since that's in the forum URL) but only one (in content/introduction/usage.md) really merits a direct link to the help section. Changed that one under #283.
- 27 results for "help" but nothing relevant other than the one already changed above.

**Comment by jessicaschilling** [comment]
Added help category description in forums, plus edited all category descriptions for consistency. Closing this issue.
