### ISSUE TITLE
Docs, Docs, Docs!

### ISSUE THREAD

**Issue by mikeal** [ipfs/docs#349]
Kicking off a discussion here about IPFS documentation.

We have a *lot* of things written down in a lot of different places :) Let's use this thread to get a complete list of the existing documentation and links to any prior audits or our documentation.

Also, I'd like us to start thinking about how to classify the consumers of our documentation so that we can prioritize which consumers we are addressing in the short term an which resources they are *already* finding so that we can target the right entry points.

**Comment by jessicaschilling** [comment]
This issue essentially encapsulates the docs WG’s Q3 and Q4 work, so closing with the suggestion that anyone following have a look at this repo’s readme for an explanation of current endeavors and prior foundation (particularly using our goal-based personae to prioritize writing efforts in order to impact the largest number of users).

Note that the inspirational links in this thread have been captured in the WG’s working spreadsheet of good references as we build out the new platform: https://docs.google.com/spreadsheets/d/1H_aDC5NHRYaoIYgUlWzqt9duhpm5qlYrx-_eLf0SETU
