### ISSUE TITLE
File with Google's Change of Address too.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/docs#514]
Tell Google that the domain for docs-beta.ipfs.io has changed, using their [Change of Address tool](https://support.google.com/webmasters/answer/9370220?hl=en&visit_id=637115245592733123-1252940477&rd=1).

**Comment by cwaring** [comment]
the beta site is currently intentionally blocked from spidering. see [robots.txt](https://github.com/ipfs/ipfs-docs-v2/blob/master/docs/.vuepress/public/robots.txt) and the meta link in [head.js](https://github.com/ipfs/ipfs-docs-v2/blob/master/docs/.vuepress/head.js#L2).

⚠️ both of these items need to be removed before public transfer to docs.ipfs.io in order to retain SEO positions

**Comment by cwaring** [comment]
(therefore you won't need to use the notifier tool - if the redirects are setup correctly any spiders will do their thing and update the indexes)

**Comment by johnnymatthews** [comment]
Excellent. I'll close this one. Cheers for your input @cwaring.
